---
- name: Get timedatectl information
  shell: timedatectl || ls -l /etc/localtime
  register: timedatectl

- name: Set timezone to UTC
  shell: (timedatectl set-timezone UTC && timedatectl) || (rm -f /etc/localtime; ln -sf /usr/share/zoneinfo/UTC /etc/localtime)
  register: timedatectl_utc
  changed_when: "'Time zone: UTC' in timedatectl_utc.stdout"
  when: "'Time zone: UTC' not in timedatectl.stdout"

- name: Set Hardware to using UTC (local RTC)
  shell: timedatectl set-local-rtc 0 && timedatectl || true
  register: timedatectl_rtc
  changed_when: "'RTC in local TZ: no' in timedatectl_rtc.stdout"
  when: "'RTC in local TZ: no' not in timedatectl.stdout"

- name: Install ntp package
  action: "{{ ansible_pkg_mgr }}"
  args:
    name: "{{ item }}"
    state: latest
  with_items:
   - ntp
   - ntpdate

- name: Remove ntpdate package
  action: "{{ ansible_pkg_mgr }}"
  args:
    name: "{{ item }}"
    state: latest
  with_items:
   - ntpdate

- name: Write ntp.conf
  template:
    src: "{{ item }}.j2"
    dest: "/etc/{{ item }}"
    mode: 0644
  with_items:
    - ntp.conf
  notify:
    - restart ntpd (rhel)
    - restart ntpd (deb)
