---
- name: Install ntp package
  action: "{{ ansible_pkg_mgr }}"
  args:
    name: "{{ item }}"
    state: latest
  with_items:
   - ntp
  notify:
    - enable ntpd (rhel)
    - enable ntp (deb)
  tags: install

- name: Write ntp.conf
  template:
    src: "ntp.conf.j2"
    dest: "/etc/ntp.conf"
    mode: 0644
  notify:
    - restart ntpd (rhel)
    - restart ntp (deb)
  tags: configure

- name: Create ntp driftfile folder
  file:
    state: directory
    path: "{{ ntp_driftfile_directory }}"
    mode: 0644
    owner: ntp
    group: ntp
  tags: configure
