---
# Handler to handle ntpd notifications
- name: enable and restart ntpd (rhel)
  service:
    name: ntpd
    enabled: yes
    state: restarted
  when: ansible_distribution != "Debian" and ansible_distribution != "Ubuntu"

- name: enable and restart ntpd (deb)
  service:
    name: ntp
    enabled: yes
    state: restarted
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: start ntpd (rhel)
  service:
    name: ntpd
    enabled: yes
    state: started
  when: ansible_distribution != "Debian" and ansible_distribution != "Ubuntu"

- name: start ntpd (deb)
  service:
    name: ntp
    enabled: yes
    state: started
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
