---
# Handler to handle ntpd notifications
- name: enable ntpd (rhel)
  service:
    name: ntpd
    enabled: yes
  when: ansible_distribution != "Debian" and ansible_distribution != "Ubuntu"

- name: enable ntpd (deb)
  service:
    name: ntp
    enabled: yes
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: restart ntpd (rhel)
  service:
    name: ntpd
    enabled: yes
    state: restarted
  when: ansible_distribution != "Debian" and ansible_distribution != "Ubuntu"

- name: restart ntpd (deb)
  service:
    name: ntp
    enabled: yes
    state: restarted
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
